export const LISTA_PAISES_OMIE = [
  {
    cCodigo: "132",
    cCodigoISO: "AF",
    cDescricao: "Afeganistão",
  },
  {
    cCodigo: "7560",
    cCodigoISO: "ZA",
    cDescricao: "África do Sul",
  },
  {
    cCodigo: "9001",
    cCodigoISO: "AX",
    cDescricao: "Aland, Ilhas",
  },
  {
    cCodigo: "175",
    cCodigoISO: "AL",
    cDescricao: "Albânia",
  },
  {
    cCodigo: "230",
    cCodigoISO: "DE",
    cDescricao: "Alemanha",
  },
  {
    cCodigo: "370",
    cCodigoISO: "AD",
    cDescricao: "Andorra",
  },
  {
    cCodigo: "400",
    cCodigoISO: "AO",
    cDescricao: "Angola",
  },
  {
    cCodigo: "418",
    cCodigoISO: "AI",
    cDescricao: "Anguilla",
  },
  {
    cCodigo: "9002",
    cCodigoISO: "AQ",
    cDescricao: "Antártica",
  },
  {
    cCodigo: "434",
    cCodigoISO: "AG",
    cDescricao: "Antigua e Barbuda",
  },
  {
    cCodigo: "477",
    cCodigoISO: "AN",
    cDescricao: "Antilhas Holandesas",
  },
  {
    cCodigo: "531",
    cCodigoISO: "SA",
    cDescricao: "Arábia Saudita",
  },
  {
    cCodigo: "590",
    cCodigoISO: "DZ",
    cDescricao: "Argélia",
  },
  {
    cCodigo: "639",
    cCodigoISO: "AR",
    cDescricao: "Argentina",
  },
  {
    cCodigo: "647",
    cCodigoISO: "AM",
    cDescricao: "Armênia",
  },
  {
    cCodigo: "655",
    cCodigoISO: "AW",
    cDescricao: "Aruba",
  },
  {
    cCodigo: "698",
    cCodigoISO: "AU",
    cDescricao: "Austrália",
  },
  {
    cCodigo: "728",
    cCodigoISO: "AT",
    cDescricao: "Áustria",
  },
  {
    cCodigo: "736",
    cCodigoISO: "AZ",
    cDescricao: "Azerbaijão",
  },
  {
    cCodigo: "779",
    cCodigoISO: "BS",
    cDescricao: "Bahamas, Ilhas",
  },
  {
    cCodigo: "809",
    cCodigoISO: "BH",
    cDescricao: "Bahrein, Ilhas",
  },
  {
    cCodigo: "817",
    cCodigoISO: "BD",
    cDescricao: "Bangladesh",
  },
  {
    cCodigo: "833",
    cCodigoISO: "BB",
    cDescricao: "Barbados",
  },
  {
    cCodigo: "850",
    cCodigoISO: "BY",
    cDescricao: "Belarus",
  },
  {
    cCodigo: "876",
    cCodigoISO: "BE",
    cDescricao: "Bélgica",
  },
  {
    cCodigo: "884",
    cCodigoISO: "BZ",
    cDescricao: "Belize",
  },
  {
    cCodigo: "2291",
    cCodigoISO: "BJ",
    cDescricao: "Benin",
  },
  {
    cCodigo: "906",
    cCodigoISO: "BM",
    cDescricao: "Bermudas",
  },
  {
    cCodigo: "973",
    cCodigoISO: "BO",
    cDescricao: "Bolívia",
  },
  {
    cCodigo: "981",
    cCodigoISO: "BA",
    cDescricao: "Bósnia-Herzegovina",
  },
  {
    cCodigo: "1015",
    cCodigoISO: "BW",
    cDescricao: "Botsuana",
  },
  {
    cCodigo: "9003",
    cCodigoISO: "BV",
    cDescricao: "Bouvet, Ilhas",
  },
  {
    cCodigo: "1058",
    cCodigoISO: "BR",
    cDescricao: "Brasil",
  },
  {
    cCodigo: "1082",
    cCodigoISO: "BN",
    cDescricao: "Brunei",
  },
  {
    cCodigo: "1112",
    cCodigoISO: "BG",
    cDescricao: "Bulgária",
  },
  {
    cCodigo: "310",
    cCodigoISO: "BF",
    cDescricao: "Burkina Faso",
  },
  {
    cCodigo: "1155",
    cCodigoISO: "BI",
    cDescricao: "Burundi",
  },
  {
    cCodigo: "1198",
    cCodigoISO: "BT",
    cDescricao: "Butão",
  },
  {
    cCodigo: "1279",
    cCodigoISO: "CV",
    cDescricao: "Cabo Verde, República de",
  },
  {
    cCodigo: "1457",
    cCodigoISO: "CM",
    cDescricao: "Camarões",
  },
  {
    cCodigo: "1414",
    cCodigoISO: "KH",
    cDescricao: "Camboja",
  },
  {
    cCodigo: "1490",
    cCodigoISO: "CA",
    cDescricao: "Canadá",
  },
  {
    cCodigo: "1511",
    cCodigoISO: "",
    cDescricao: "Canárias, Ilhas",
  },
  {
    cCodigo: "1546",
    cCodigoISO: "QA",
    cDescricao: "Catar",
  },
  {
    cCodigo: "1376",
    cCodigoISO: "KY",
    cDescricao: "Cayman, Ilhas",
  },
  {
    cCodigo: "1538",
    cCodigoISO: "KZ",
    cDescricao: "Cazaquistão",
  },
  {
    cCodigo: "7889",
    cCodigoISO: "TD",
    cDescricao: "Chade",
  },
  {
    cCodigo: "1589",
    cCodigoISO: "CL",
    cDescricao: "Chile",
  },
  {
    cCodigo: "1600",
    cCodigoISO: "CN",
    cDescricao: "China",
  },
  {
    cCodigo: "1635",
    cCodigoISO: "CY",
    cDescricao: "Chipre",
  },
  {
    cCodigo: "5118",
    cCodigoISO: "CX",
    cDescricao: "Christmas,Ilha (Navidad)",
  },
  {
    cCodigo: "1651",
    cCodigoISO: "CC",
    cDescricao: "Cocos (Keeling), Ilhas",
  },
  {
    cCodigo: "1694",
    cCodigoISO: "CO",
    cDescricao: "Colômbia",
  },
  {
    cCodigo: "1732",
    cCodigoISO: "KM",
    cDescricao: "Comores, Ilhas",
  },
  {
    cCodigo: "1775",
    cCodigoISO: "CG",
    cDescricao: "Congo (Brazzaville)",
  },
  {
    cCodigo: "8885",
    cCodigoISO: "CD",
    cDescricao: "Congo (Kinshasa)",
  },
  {
    cCodigo: "1830",
    cCodigoISO: "CK",
    cDescricao: "Cook, Ilhas",
  },
  {
    cCodigo: "1872",
    cCodigoISO: "KP",
    cDescricao: "Coréia do Norte",
  },
  {
    cCodigo: "1902",
    cCodigoISO: "KR",
    cDescricao: "Coréia do Sul",
  },
  {
    cCodigo: "1937",
    cCodigoISO: "CI",
    cDescricao: "Costa do Marfim",
  },
  {
    cCodigo: "1961",
    cCodigoISO: "CR",
    cDescricao: "Costa Rica",
  },
  {
    cCodigo: "1988",
    cCodigoISO: "KW",
    cDescricao: "Coveite (Kuwait)",
  },
  {
    cCodigo: "1953",
    cCodigoISO: "HR",
    cDescricao: "Croácia",
  },
  {
    cCodigo: "1996",
    cCodigoISO: "CU",
    cDescricao: "Cuba",
  },
  {
    cCodigo: "2003",
    cCodigoISO: "CW",
    cDescricao: "Curaçao",
  },
  {
    cCodigo: "2321",
    cCodigoISO: "DK",
    cDescricao: "Dinamarca",
  },
  {
    cCodigo: "7838",
    cCodigoISO: "DJ",
    cDescricao: "Djibuti",
  },
  {
    cCodigo: "2356",
    cCodigoISO: "DM",
    cDescricao: "Dominica, Ilha",
  },
  {
    cCodigo: "2402",
    cCodigoISO: "EG",
    cDescricao: "Egito",
  },
  {
    cCodigo: "6874",
    cCodigoISO: "SV",
    cDescricao: "El Salvador",
  },
  {
    cCodigo: "2445",
    cCodigoISO: "AE",
    cDescricao: "Emirados Árabes Unidos",
  },
  {
    cCodigo: "2399",
    cCodigoISO: "EC",
    cDescricao: "Equador",
  },
  {
    cCodigo: "2437",
    cCodigoISO: "ER",
    cDescricao: "Eritréia",
  },
  {
    cCodigo: "2470",
    cCodigoISO: "SK",
    cDescricao: "Eslovaca, República",
  },
  {
    cCodigo: "2461",
    cCodigoISO: "SI",
    cDescricao: "Eslovênia",
  },
  {
    cCodigo: "2453",
    cCodigoISO: "ES",
    cDescricao: "Espanha",
  },
  {
    cCodigo: "2496",
    cCodigoISO: "US",
    cDescricao: "Estados Unidos",
  },
  {
    cCodigo: "2518",
    cCodigoISO: "EE",
    cDescricao: "Estônia",
  },
  {
    cCodigo: "2534",
    cCodigoISO: "ET",
    cDescricao: "Etiópia",
  },
  {
    cCodigo: "2550",
    cCodigoISO: "FK",
    cDescricao: "Falkland (Ilhas Malvinas)",
  },
  {
    cCodigo: "2593",
    cCodigoISO: "FO",
    cDescricao: "Feroe, Ilhas",
  },
  {
    cCodigo: "8702",
    cCodigoISO: "FJ",
    cDescricao: "Fiji",
  },
  {
    cCodigo: "2674",
    cCodigoISO: "PH",
    cDescricao: "Filipinas",
  },
  {
    cCodigo: "2712",
    cCodigoISO: "FI",
    cDescricao: "Finlândia",
  },
  {
    cCodigo: "1619",
    cCodigoISO: "TW",
    cDescricao: "Formosa (Taiwan)",
  },
  {
    cCodigo: "2755",
    cCodigoISO: "FR",
    cDescricao: "França",
  },
  {
    cCodigo: "2810",
    cCodigoISO: "GA",
    cDescricao: "Gabão",
  },
  {
    cCodigo: "2852",
    cCodigoISO: "GM",
    cDescricao: "Gâmbia",
  },
  {
    cCodigo: "2895",
    cCodigoISO: "GH",
    cDescricao: "Gana",
  },
  {
    cCodigo: "2917",
    cCodigoISO: "GE",
    cDescricao: "Geórgia",
  },
  {
    cCodigo: "9011",
    cCodigoISO: "GS",
    cDescricao: "Geórgia/Sandwich do Sul, Ilhas",
  },
  {
    cCodigo: "2933",
    cCodigoISO: "GI",
    cDescricao: "Gibraltar",
  },
  {
    cCodigo: "2976",
    cCodigoISO: "GD",
    cDescricao: "Granada",
  },
  {
    cCodigo: "3018",
    cCodigoISO: "GR",
    cDescricao: "Grécia",
  },
  {
    cCodigo: "3050",
    cCodigoISO: "GL",
    cDescricao: "Groenlândia",
  },
  {
    cCodigo: "3093",
    cCodigoISO: "GP",
    cDescricao: "Guadalupe",
  },
  {
    cCodigo: "3131",
    cCodigoISO: "GU",
    cDescricao: "Guam",
  },
  {
    cCodigo: "3174",
    cCodigoISO: "GT",
    cDescricao: "Guatemala",
  },
  {
    cCodigo: "3212",
    cCodigoISO: "GG",
    cDescricao: "Guernsey",
  },
  {
    cCodigo: "3379",
    cCodigoISO: "GY",
    cDescricao: "Guiana",
  },
  {
    cCodigo: "3255",
    cCodigoISO: "GF",
    cDescricao: "Guiana Francesa",
  },
  {
    cCodigo: "3298",
    cCodigoISO: "GN",
    cDescricao: "Guiné",
  },
  {
    cCodigo: "3344",
    cCodigoISO: "GW",
    cDescricao: "Guiné-Bissau",
  },
  {
    cCodigo: "3310",
    cCodigoISO: "GQ",
    cDescricao: "Guiné-Equatorial",
  },
  {
    cCodigo: "3417",
    cCodigoISO: "HT",
    cDescricao: "Haiti",
  },
  {
    cCodigo: "9006",
    cCodigoISO: "HM",
    cDescricao: "Heard e Mcdonald, Ilhas",
  },
  {
    cCodigo: "3450",
    cCodigoISO: "HN",
    cDescricao: "Honduras",
  },
  {
    cCodigo: "3514",
    cCodigoISO: "HK",
    cDescricao: "Hong Kong",
  },
  {
    cCodigo: "3557",
    cCodigoISO: "HU",
    cDescricao: "Hungria",
  },
  {
    cCodigo: "3573",
    cCodigoISO: "YE",
    cDescricao: "Iêmen",
  },
  {
    cCodigo: "3611",
    cCodigoISO: "IN",
    cDescricao: "Índia",
  },
  {
    cCodigo: "3654",
    cCodigoISO: "ID",
    cDescricao: "Indonésia",
  },
  {
    cCodigo: "3727",
    cCodigoISO: "IR",
    cDescricao: "Irã",
  },
  {
    cCodigo: "3697",
    cCodigoISO: "IQ",
    cDescricao: "Iraque",
  },
  {
    cCodigo: "3751",
    cCodigoISO: "IE",
    cDescricao: "Irlanda",
  },
  {
    cCodigo: "3794",
    cCodigoISO: "IS",
    cDescricao: "Islândia",
  },
  {
    cCodigo: "3832",
    cCodigoISO: "IL",
    cDescricao: "Israel",
  },
  {
    cCodigo: "3867",
    cCodigoISO: "IT",
    cDescricao: "Itália",
  },
  {
    cCodigo: "3913",
    cCodigoISO: "JM",
    cDescricao: "Jamaica",
  },
  {
    cCodigo: "3999",
    cCodigoISO: "JP",
    cDescricao: "Japão",
  },
  {
    cCodigo: "3930",
    cCodigoISO: "JE",
    cDescricao: "Jersey, Ilha do Canal",
  },
  {
    cCodigo: "3964",
    cCodigoISO: "",
    cDescricao: "Johnston, Ilhas",
  },
  {
    cCodigo: "4030",
    cCodigoISO: "JO",
    cDescricao: "Jordânia",
  },
  {
    cCodigo: "4111",
    cCodigoISO: "KI",
    cDescricao: "Kiribati",
  },
  {
    cCodigo: "4200",
    cCodigoISO: "LA",
    cDescricao: "Laos",
  },
  {
    cCodigo: "4235",
    cCodigoISO: "",
    cDescricao: "Lebuan, Ilhas",
  },
  {
    cCodigo: "4260",
    cCodigoISO: "LS",
    cDescricao: "Lesoto",
  },
  {
    cCodigo: "4278",
    cCodigoISO: "LV",
    cDescricao: "Letônia",
  },
  {
    cCodigo: "4316",
    cCodigoISO: "LB",
    cDescricao: "Líbano",
  },
  {
    cCodigo: "4340",
    cCodigoISO: "LR",
    cDescricao: "Libéria",
  },
  {
    cCodigo: "4383",
    cCodigoISO: "LY",
    cDescricao: "Líbia",
  },
  {
    cCodigo: "4405",
    cCodigoISO: "LI",
    cDescricao: "Liechtenstein",
  },
  {
    cCodigo: "4421",
    cCodigoISO: "LT",
    cDescricao: "Lituânia",
  },
  {
    cCodigo: "4456",
    cCodigoISO: "LU",
    cDescricao: "Luxemburgo",
  },
  {
    cCodigo: "4472",
    cCodigoISO: "MO",
    cDescricao: "Macau",
  },
  {
    cCodigo: "4499",
    cCodigoISO: "MK",
    cDescricao: "Macedônia, Republica da",
  },
  {
    cCodigo: "4502",
    cCodigoISO: "MG",
    cDescricao: "Madagascar",
  },
  {
    cCodigo: "4525",
    cCodigoISO: "",
    cDescricao: "Madeira, Ilha da",
  },
  {
    cCodigo: "4553",
    cCodigoISO: "MY",
    cDescricao: "Malásia",
  },
  {
    cCodigo: "4588",
    cCodigoISO: "MW",
    cDescricao: "Malavi",
  },
  {
    cCodigo: "4618",
    cCodigoISO: "MV",
    cDescricao: "Maldivas",
  },
  {
    cCodigo: "4642",
    cCodigoISO: "ML",
    cDescricao: "Mali",
  },
  {
    cCodigo: "4677",
    cCodigoISO: "MT",
    cDescricao: "Malta",
  },
  {
    cCodigo: "3595",
    cCodigoISO: "IM",
    cDescricao: "Man, Ilha de",
  },
  {
    cCodigo: "4723",
    cCodigoISO: "MP",
    cDescricao: "Marianas do Norte",
  },
  {
    cCodigo: "4740",
    cCodigoISO: "MA",
    cDescricao: "Marrocos",
  },
  {
    cCodigo: "4766",
    cCodigoISO: "MH",
    cDescricao: "Marshall, Ilhas",
  },
  {
    cCodigo: "4774",
    cCodigoISO: "MQ",
    cDescricao: "Martinica",
  },
  {
    cCodigo: "4855",
    cCodigoISO: "MU",
    cDescricao: "Maurício",
  },
  {
    cCodigo: "4880",
    cCodigoISO: "MR",
    cDescricao: "Mauritânia",
  },
  {
    cCodigo: "4885",
    cCodigoISO: "YT",
    cDescricao: "Mayotte (Ilhas Francesas)",
  },
  {
    cCodigo: "9014",
    cCodigoISO: "UM",
    cDescricao: "Menores Distantes EUA, Ilhas",
  },
  {
    cCodigo: "4936",
    cCodigoISO: "MX",
    cDescricao: "México",
  },
  {
    cCodigo: "930",
    cCodigoISO: "MM",
    cDescricao: "Mianmar (Birmânia)",
  },
  {
    cCodigo: "4995",
    cCodigoISO: "FM",
    cDescricao: "Micronésia",
  },
  {
    cCodigo: "4901",
    cCodigoISO: "",
    cDescricao: "Midway, Ilhas",
  },
  {
    cCodigo: "5053",
    cCodigoISO: "MZ",
    cDescricao: "Moçambique",
  },
  {
    cCodigo: "4944",
    cCodigoISO: "MD",
    cDescricao: "Moldávia",
  },
  {
    cCodigo: "4952",
    cCodigoISO: "MC",
    cDescricao: "Mônaco",
  },
  {
    cCodigo: "4979",
    cCodigoISO: "MN",
    cDescricao: "Mongólia",
  },
  {
    cCodigo: "4985",
    cCodigoISO: "ME",
    cDescricao: "Montenegro",
  },
  {
    cCodigo: "5010",
    cCodigoISO: "MS",
    cDescricao: "Montserrat, Ilhas",
  },
  {
    cCodigo: "5070",
    cCodigoISO: "NA",
    cDescricao: "Namíbia",
  },
  {
    cCodigo: "5088",
    cCodigoISO: "NR",
    cDescricao: "Nauru",
  },
  {
    cCodigo: "5177",
    cCodigoISO: "NP",
    cDescricao: "Nepal",
  },
  {
    cCodigo: "5215",
    cCodigoISO: "NI",
    cDescricao: "Nicarágua",
  },
  {
    cCodigo: "5258",
    cCodigoISO: "NE",
    cDescricao: "Niger",
  },
  {
    cCodigo: "5282",
    cCodigoISO: "NG",
    cDescricao: "Nigéria",
  },
  {
    cCodigo: "5312",
    cCodigoISO: "NU",
    cDescricao: "Niue,Ilha",
  },
  {
    cCodigo: "5355",
    cCodigoISO: "NF",
    cDescricao: "Norfolk,Ilha",
  },
  {
    cCodigo: "5380",
    cCodigoISO: "NO",
    cDescricao: "Noruega",
  },
  {
    cCodigo: "5428",
    cCodigoISO: "NC",
    cDescricao: "Nova Caledônia",
  },
  {
    cCodigo: "5487",
    cCodigoISO: "NZ",
    cDescricao: "Nova Zelândia",
  },
  {
    cCodigo: "5568",
    cCodigoISO: "OM",
    cDescricao: "Omã",
  },
  {
    cCodigo: "5738",
    cCodigoISO: "NL",
    cDescricao: "Países Baixos (Holanda)",
  },
  {
    cCodigo: "5754",
    cCodigoISO: "PW",
    cDescricao: "Palau",
  },
  {
    cCodigo: "5780",
    cCodigoISO: "PS",
    cDescricao: "Palestina",
  },
  {
    cCodigo: "5800",
    cCodigoISO: "PA",
    cDescricao: "Panamá",
  },
  {
    cCodigo: "5452",
    cCodigoISO: "PG",
    cDescricao: "Papua Nova Guiné",
  },
  {
    cCodigo: "5762",
    cCodigoISO: "PK",
    cDescricao: "Paquistão",
  },
  {
    cCodigo: "5860",
    cCodigoISO: "PY",
    cDescricao: "Paraguai",
  },
  {
    cCodigo: "5894",
    cCodigoISO: "PE",
    cDescricao: "Peru",
  },
  {
    cCodigo: "5932",
    cCodigoISO: "PN",
    cDescricao: "Pitcairn, Ilha",
  },
  {
    cCodigo: "5991",
    cCodigoISO: "PF",
    cDescricao: "Polinésia Francesa",
  },
  {
    cCodigo: "6033",
    cCodigoISO: "PL",
    cDescricao: "Polônia",
  },
  {
    cCodigo: "6114",
    cCodigoISO: "PR",
    cDescricao: "Porto Rico",
  },
  {
    cCodigo: "6076",
    cCodigoISO: "PT",
    cDescricao: "Portugal",
  },
  {
    cCodigo: "6238",
    cCodigoISO: "KE",
    cDescricao: "Quênia",
  },
  {
    cCodigo: "6254",
    cCodigoISO: "KG",
    cDescricao: "Quirguiz, República",
  },
  {
    cCodigo: "6289",
    cCodigoISO: "GB",
    cDescricao: "Reino Unido",
  },
  {
    cCodigo: "6408",
    cCodigoISO: "CF",
    cDescricao: "República Centro-Africana",
  },
  {
    cCodigo: "6475",
    cCodigoISO: "DO",
    cDescricao: "República Dominicana",
  },
  {
    cCodigo: "6602",
    cCodigoISO: "RE",
    cDescricao: "Reunião, Ilha",
  },
  {
    cCodigo: "6700",
    cCodigoISO: "RO",
    cDescricao: "Romênia",
  },
  {
    cCodigo: "6750",
    cCodigoISO: "RW",
    cDescricao: "Ruanda",
  },
  {
    cCodigo: "6769",
    cCodigoISO: "RU",
    cDescricao: "Rússia",
  },
  {
    cCodigo: "6858",
    cCodigoISO: "EH",
    cDescricao: "Saara Ocidental",
  },
  {
    cCodigo: "9009",
    cCodigoISO: "BL",
    cDescricao: "Saint Barthélemy",
  },
  {
    cCodigo: "663",
    cCodigoISO: "MF",
    cDescricao: "Saint-Martin (França)",
  },
  {
    cCodigo: "6777",
    cCodigoISO: "SB",
    cDescricao: "Salomão, Ilhas",
  },
  {
    cCodigo: "6904",
    cCodigoISO: "WS",
    cDescricao: "Samoa",
  },
  {
    cCodigo: "6912",
    cCodigoISO: "AS",
    cDescricao: "Samoa Americana",
  },
  {
    cCodigo: "6971",
    cCodigoISO: "SM",
    cDescricao: "San Marino",
  },
  {
    cCodigo: "7102",
    cCodigoISO: "SH",
    cDescricao: "Santa Helena",
  },
  {
    cCodigo: "7153",
    cCodigoISO: "LC",
    cDescricao: "Santa Lúcia",
  },
  {
    cCodigo: "6939",
    cCodigoISO: "SB",
    cDescricao: "São Bartolomeu",
  },
  {
    cCodigo: "6955",
    cCodigoISO: "KN",
    cDescricao: "São Cristóvão e Neves, Ilhas",
  },
  {
    cCodigo: "7005",
    cCodigoISO: "PM",
    cDescricao: "São Pedro e Miquelon",
  },
  {
    cCodigo: "7200",
    cCodigoISO: "ST",
    cDescricao: "São Tomé e Príncipe, Ilhas",
  },
  {
    cCodigo: "7056",
    cCodigoISO: "VC",
    cDescricao: "São Vicente e Granadinas",
  },
  {
    cCodigo: "7285",
    cCodigoISO: "SN",
    cDescricao: "Senegal",
  },
  {
    cCodigo: "7358",
    cCodigoISO: "SL",
    cDescricao: "Serra Leoa",
  },
  {
    cCodigo: "7370",
    cCodigoISO: "RS",
    cDescricao: "Sérvia",
  },
  {
    cCodigo: "7315",
    cCodigoISO: "SC",
    cDescricao: "Seychelles",
  },
  {
    cCodigo: "7412",
    cCodigoISO: "SG",
    cDescricao: "Singapura",
  },
  {
    cCodigo: "7447",
    cCodigoISO: "SY",
    cDescricao: "Síria",
  },
  {
    cCodigo: "7480",
    cCodigoISO: "SO",
    cDescricao: "Somália",
  },
  {
    cCodigo: "7501",
    cCodigoISO: "LK",
    cDescricao: "Sri Lanka",
  },
  {
    cCodigo: "7544",
    cCodigoISO: "SZ",
    cDescricao: "Suazilândia",
  },
  {
    cCodigo: "7595",
    cCodigoISO: "SD",
    cDescricao: "Sudão",
  },
  {
    cCodigo: "9012",
    cCodigoISO: "SS",
    cDescricao: "Sudão do Sul",
  },
  {
    cCodigo: "7641",
    cCodigoISO: "SE",
    cDescricao: "Suécia",
  },
  {
    cCodigo: "7676",
    cCodigoISO: "CH",
    cDescricao: "Suíça",
  },
  {
    cCodigo: "7706",
    cCodigoISO: "SR",
    cDescricao: "Suriname",
  },
  {
    cCodigo: "9013",
    cCodigoISO: "SJ",
    cDescricao: "Svalbard e Jan Mayen, Ilhas",
  },
  {
    cCodigo: "7722",
    cCodigoISO: "TJ",
    cDescricao: "Tadjiquistão",
  },
  {
    cCodigo: "7765",
    cCodigoISO: "TH",
    cDescricao: "Tailândia",
  },
  {
    cCodigo: "7803",
    cCodigoISO: "TZ",
    cDescricao: "Tanzânia",
  },
  {
    cCodigo: "7919",
    cCodigoISO: "CZ",
    cDescricao: "Tcheca, República",
  },
  {
    cCodigo: "9004",
    cCodigoISO: "TF",
    cDescricao: "Terras Austrais Francesas",
  },
  {
    cCodigo: "7811",
    cCodigoISO: "TF",
    cDescricao: "Terras Autrais AntarT. Frances",
  },
  {
    cCodigo: "7820",
    cCodigoISO: "IO",
    cDescricao: "Território Brit.Oc.Indico",
  },
  {
    cCodigo: "9008",
    cCodigoISO: "PS",
    cDescricao: "Território Palestino",
  },
  {
    cCodigo: "7951",
    cCodigoISO: "TL",
    cDescricao: "Timor Leste",
  },
  {
    cCodigo: "8001",
    cCodigoISO: "TG",
    cDescricao: "Togo",
  },
  {
    cCodigo: "8109",
    cCodigoISO: "TO",
    cDescricao: "Tonga",
  },
  {
    cCodigo: "8052",
    cCodigoISO: "TK",
    cDescricao: "Toquelau,Ilhas",
  },
  {
    cCodigo: "8150",
    cCodigoISO: "TT",
    cDescricao: "Trinidad e Tobago",
  },
  {
    cCodigo: "8206",
    cCodigoISO: "TN",
    cDescricao: "Tunísia",
  },
  {
    cCodigo: "8230",
    cCodigoISO: "TC",
    cDescricao: "Turcas e Caicos, Ilhas",
  },
  {
    cCodigo: "8249",
    cCodigoISO: "TM",
    cDescricao: "Turcomenistão",
  },
  {
    cCodigo: "8273",
    cCodigoISO: "TR",
    cDescricao: "Turquia",
  },
  {
    cCodigo: "8281",
    cCodigoISO: "TV",
    cDescricao: "Tuvalu",
  },
  {
    cCodigo: "8311",
    cCodigoISO: "UA",
    cDescricao: "Ucrânia",
  },
  {
    cCodigo: "8338",
    cCodigoISO: "UG",
    cDescricao: "Uganda",
  },
  {
    cCodigo: "8451",
    cCodigoISO: "UY",
    cDescricao: "Uruguai",
  },
  {
    cCodigo: "8478",
    cCodigoISO: "UZ",
    cDescricao: "Uzbequistão",
  },
  {
    cCodigo: "5517",
    cCodigoISO: "VU",
    cDescricao: "Vanuatu",
  },
  {
    cCodigo: "8486",
    cCodigoISO: "VA",
    cDescricao: "Vaticano, Estado Cidade",
  },
  {
    cCodigo: "8508",
    cCodigoISO: "VE",
    cDescricao: "Venezuela",
  },
  {
    cCodigo: "8583",
    cCodigoISO: "VN",
    cDescricao: "Vietnã",
  },
  {
    cCodigo: "8630",
    cCodigoISO: "VG",
    cDescricao: "Virgens,Ilhas (Britânicas)",
  },
  {
    cCodigo: "8664",
    cCodigoISO: "VI",
    cDescricao: "Virgens,Ilhas (E.U.A.)",
  },
  {
    cCodigo: "8737",
    cCodigoISO: "",
    cDescricao: "Wake, Ilha",
  },
  {
    cCodigo: "9015",
    cCodigoISO: "WF",
    cDescricao: "Wallis e Futuna, Ilhas",
  },
  {
    cCodigo: "8907",
    cCodigoISO: "ZM",
    cDescricao: "Zâmbia",
  },
  {
    cCodigo: "6653",
    cCodigoISO: "ZW",
    cDescricao: "Zimbábue",
  },
];

export const LISTA_ESTADOS = [
  { label: "Acre", value: "AC" },
  { label: "Alagoas", value: "AL" },
  { label: "Amapá", value: "AP" },
  { label: "Amazonas", value: "AM" },
  { label: "Bahia", value: "BA" },
  { label: "Ceará", value: "CE" },
  { label: "Distrito Federal", value: "DF" },
  { label: "Espírito Santo", value: "ES" },
  { label: "Goiás", value: "GO" },
  { label: "Maranhão", value: "MA" },
  { label: "Mato Grosso", value: "MT" },
  { label: "Mato Grosso do Sul", value: "MS" },
  { label: "Minas Gerais", value: "MG" },
  { label: "Pará", value: "PA" },
  { label: "Paraíba", value: "PB" },
  { label: "Paraná", value: "PR" },
  { label: "Pernambuco", value: "PE" },
  { label: "Piauí", value: "PI" },
  { label: "Rio de Janeiro", value: "RJ" },
  { label: "Rio Grande do Norte", value: "RN" },
  { label: "Rio Grande do Sul", value: "RS" },
  { label: "Rondônia", value: "RO" },
  { label: "Roraima", value: "RR" },
  { label: "Santa Catarina", value: "SC" },
  { label: "São Paulo", value: "SP" },
  { label: "Sergipe", value: "SE" },
  { label: "Tocantins", value: "TO" },
  { label: "Exterior", value: "EX" },
];
